#!/bin/sh
user_home="$USERPROFILE"
makecmd="make -r"

debug="0"
release="0"
run="1"

CONFIG_PATH=`pwd`/config.sh

[[ -f "$CONFIG_PATH" ]] && source "$CONFIG_PATH"

DEBUG_SHARED="-DDEBUG_PRELOADER_SANITY=1 -O0 -ffast-math -ggdb -Werror=return-type -DDEBUG=1 -D_DEBUG_DUMP $EXTRA_DEBUGFLAGS_SHARED"

DEBUGFLAGS_CC="$DEBUG_SHARED $EXTRA_DEBUGFLAGS_CC"
DEBUGFLAGS_CXX="$DEBUG_SHARED $EXTRA_DEBUGFLAGS_CXX"
DEBUGFLAGS_LD="$EXTRA_DEBUGFLAGS_LD"

RELEASE_SHARED="-ffast-math -DNDEBUG=1 -s -fomit-frame-pointer -fvisibility=hidden -fdata-sections -ffunction-sections"

RELEASEFLAGS_CC="$RELEASE_SHARED -O1 $EXTRA_RELEASEFLAGS_CC"
RELEASEFLAGS_CXX="$RELEASE_SHARED -O2 -fvisibility-inlines-hidden -fno-rtti $EXTRA_RELEASEFLAGS_CXX"
RELEASEFLAGS_LD="-Wl,-O,-s,--gc-sections $EXTRA_RELEASEFLAGS_LD"

CFLAGS="$DEBUGFLAGS"
CXXFLAGS="$CFLAGS"
CPPFLAGS="$CFLAGS"

skipmake="false"

while test $# -gt 0; do
    case "$1" in
        --clean)
            echo "cleaning"
            $makecmd clean
            exit
            ;;
        -f|--fastcompile)
            mingw32-make CFLAGS="$DEBUGFLAGS_CC" CXXFLAGS="$DEBUGFLAGS_CXX" -j5
            exit
            ;;
        -s|--silent)
            echo "only compiling"
            run="0"
            shift
            ;;
        -x|--exec)
            echo "only executing"
            skipmake="true"
            shift
            ;;
        -g|--gdb)
            debug="1"
            shift
            ;;
        -v|--valgrind)
            debug="2"
            shift
            ;;
        --drmemory)
            debug="2"
            shift
            ;;
        -r|--release)
            release="1"
            shift
            ;;
    esac
done

if [ "$release" -eq "1" ]; then
    CFLAGS="$RELEASEFLAGS_CC"
    CXXFLAGS="$RELEASEFLAGS_CXX"
    CPPFLAGS="$RELEASEFLAGS_CXX"
    LDFLAGS="$RELEASEFLAGS_LD"
    mingw32-make CFLAGS="$RELEASEFLAGS_CC" CXXFLAGS="$RELEASEFLAGS_CXX" LDFLAGS="$RELEASEFLAGS_LD" -j9
    $makecmd CFLAGS="$RELEASEFLAGS_CC" CXXFLAGS="$RELEASEFLAGS_CXX" LDFLAGS="$RELEASEFLAGS_LD"
    exit
fi

($skipmake || $makecmd CFLAGS="$DEBUGFLAGS_CC" CXXFLAGS="$DEBUGFLAGS_CXX" -j9 ) &&
if [ "$run" -eq "1" ]; then
    if [ "$debug" -eq "2" ]; then
        drmemory -logdir ./drmemory -- principia
    elif [ "$debug" -eq "1" ]; then
        gdb principia
    else
        principia
    fi
fi
