#ifndef _VERSION__H_
#define _VERSION__H_

#define PRINCIPIA_VERSION_CODE 34
#define PRINCIPIA_VERSION_CODE_STRING STR(PRINCIPIA_VERSION_CODE)
#define _COOL_VERSION_STRING "1.5.1"
#ifdef DEBUG
#define PRINCIPIA_VERSION_STRING "(debug) " _COOL_VERSION_STRING
#else
#define PRINCIPIA_VERSION_STRING _COOL_VERSION_STRING
#endif

#define PRINCIPIA_STRING "Principia"

#define PRINCIPIA_USERAGENT PRINCIPIA_STRING "/" STR(PRINCIPIA_VERSION_CODE) " (" OS_STRING ")"

#endif
