env:
  matrix:
    - JANSSON_BUILD_METHOD=cmake JANSSON_CMAKE_OPTIONS="-DJANSSON_TEST_WITH_VALGRIND=ON" JANSSON_EXTRA_INSTALL="valgrind"
    - JANSSON_BUILD_METHOD=autotools
language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake $JANSSON_EXTRA_INSTALL
script:
  - if [ "$JANSSON_BUILD_METHOD" = "autotools" ]; then autoreconf -f -i && CFLAGS=-Werror ./configure && make check; fi
  - if [ "$JANSSON_BUILD_METHOD" = "cmake" ]; then mkdir build && cd build && cmake .. $JANSSON_CMAKE_OPTIONS && cmake --build . && ctest --output-on-failure; fi
