#!/bin/sh
user_home="$HOME"
makecmd="make"

debug="0"
run="0"
num_jobs="3"

CONFIG_PATH=`pwd`/config.sh

[[ -f "$CONFIG_PATH" ]] && source "$CONFIG_PATH"

SHARED_FLAGS="-ffast-math -Wno-unused-result"

DEBUGFLAGS="-O0 -ggdb $SHARED_FLAGS"
RELEASEFLAGS="-O0 $SHARED_FLAGS"

CFLAGS="$DEBUGFLAGS"
CXXFLAGS="$CFLAGS"
CPPFLAGS="$CFLAGS"

while test $# -gt 0; do
    case "$1" in
        --clean)
            echo "cleaning"
            $makecmd clean
            exit
            ;;
        --run)
            run="1"
            break
            ;;
        -g|--gdb)
            debug="1"
            break
            ;;
        -v|--valgrind)
            debug="2"
            break
            ;;
        -c|--cachegrind)
            debug="3"
            run="1"
            break
            ;;
        *)
            echo "undefined option: $1"
            shift
            ;;
    esac
done

$makecmd CFLAGS="$RELEASEFLAGS" CXXFLAGS="$RELEASEFLAGS" -j $num_jobs &&
if [ "$run" -eq "1" ]; then
    if [ "$debug" -eq "2" ]; then
        valgrind ./principia_ss 50000
    elif [ "$debug" -eq "1" ]; then
        gdb --args ./principia_ss 50000
    elif [ "$debug" -eq "3" ]; then
        rm callgrind.* &> /dev/null
        valgrind --tool=callgrind -v --dump-every-bb=10000000 ./principia_ss
        gdb --args ./principia_ss 50000
    else
        ./principia_ss 50000
    fi
fi
