set(DEPS "${CMAKE_SOURCE_DIR}/android/deps/${ANDROID_ABI}")

set(CURL_INCLUDE_DIR ${DEPS}/include)
set(CURL_LIBRARY ${DEPS}/libcurl.a;${DEPS}/libmbedcrypto.a;${DEPS}/libmbedtls.a;${DEPS}/libmbedx509.a)
set(FREETYPE_INCLUDE_DIR_ft2build ${DEPS}/include/freetype2)
set(FREETYPE_INCLUDE_DIR_freetype2 ${FREETYPE_INCLUDE_DIR_ft2build}/freetype)
set(FREETYPE_LIBRARY ${DEPS}/libfreetype.a)
set(JPEG_INCLUDE_DIR ${DEPS}/include)
set(JPEG_LIBRARY ${DEPS}/libjpeg.a)
set(PNG_PNG_INCLUDE_DIR ${DEPS}/include)
set(PNG_LIBRARY ${DEPS}/libpng.a)
