name: android

on:
  push:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'android/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'android/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/android.yml'

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Build with gradle
        run: |
          cd android
          ./gradlew assemblerelease

      - name: Save apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: principia-release-unsigned.apk
          path: android/principia/build/outputs/apk/release/principia-release-unsigned.apk
