name: linux

on:
  push:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'

jobs:
  linux:
    name: AppImage (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    container:
      image: debian/eol:bullseye
      env: { LANG: "C.UTF-8" }
    steps:
      - run: |
          echo "deb http://archive.debian.org/debian bullseye main" > /etc/apt/sources.list
          echo "deb http://snapshot.debian.org/archive/debian-security/20260831T211327Z/ bullseye-security main" >> /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian bullseye-updates main" >> /etc/apt/sources.list

      - uses: actions/checkout@v6

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y \
            clang-16 libgl-dev libcurl4-openssl-dev libpng-dev libjpeg-dev libfreetype6-dev cmake ninja-build desktop-file-utils ca-certificates wget file \
            libasound2-dev libpulse-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev liburing-dev \
            --no-install-recommends

      - name: Build
        run: |
          mkdir build; cd build
          ../packaging/install-libdecor-dev.sh ${{ matrix.arch }}
          ../packaging/build-appimage.sh ${{ matrix.arch }}
        env:
          CC: clang-16
          CXX: clang++-16

      - name: Upload output as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Principia-${{ matrix.arch }}.AppImage
          path: build/Principia-${{ matrix.arch }}.AppImage
          #archive: false
          if-no-files-found: error

      - name: Upload debug symbols as artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-appimage-dbgsym-${{ matrix.arch }}
          path: build/principia.debug
          if-no-files-found: error
