name: linux_ss

on:
  push:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/screenshotter-container/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux_ss.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/screenshotter-container/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux_ss.yml'

jobs:
  linux_ss:
    name: Screenshot build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libgl-dev libpng-dev libjpeg-dev libfreetype6-dev cmake ninja-build \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libegl1-mesa-dev \
            --no-install-recommends

      - name: Build
        run: |
          mkdir build; cd build
          cmake .. -DSCREENSHOT_BUILD=ON -DUSE_VENDORED_SDL3=ON -DUNITY_BUILD=ON -G Ninja
          ninja -j4

      - name: Upload output as artifact
        uses: actions/upload-artifact@v7
        with:
          name: screenshotter_artifact
          path: build/principia
          if-no-files-found: error

  linux_ss_docker:
    name: Screenshot build (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./packaging/screenshotter-container
          file: ./packaging/screenshotter-container/Dockerfile
          tags: principia-screenshotter:latest
          outputs: type=docker,dest=/tmp/principia-screenshotter.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v7
        with:
          name: principia-screenshotter
          path: /tmp/principia-screenshotter.tar
