# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-focal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $GITHUB_WORKSPACE

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt update # updates apt to get packages
          export DEBIAN_FRONTEND=noninteractive # this is for the timezone selection to work
          apt install y automake libgtk2.0dev libgldev libxssdev libxxf86vmdev libasound2dev libudevdev valgrind libcurl4openssldev libpngdev libjpegdev libfreetype6dev tzdata libsdl2dev libsdl2imagedev libsdl2mixerdev libsdl2gfxdev libsdl2netdev libsdl2ttfdev # installs required packages plus a few more for libsdl2, these should be added to the original deps I think
          ln fs /usr/share/zoneinfo/America/New_York /etc/localtime # sets the localtime to New York, I don't think it matters as this is ran in a contianer
          dpkgreconfigure frontend noninteractive tzdata # reconfigures timezone selection and does it
          cd buildlinux # GitLab starts at the root of the repo, so I navigate to the buildlinux folder
          ./autogen.sh # relevant scripts being run
          ./configure # same as above
          ./go clean release silent # build script
          cd .. # moves back to the repo root, as the datapc and datashared in the buildlinux folder are symlinks. This can have a better workaround from someone who is much more experienced with Linux and building
          cp buildlinux/apparatus2 . # copies the built apparatus2 binary to the repo root, this won't matter as it does not modify the repo itself
          tar czf principia.tar.gz apparatus2 datapc datashared # packs the binary, datapc and datashared into a .tar.gz file, we'll make it available as an artifact in the next step
        
