name: windows

on:
  push:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'

jobs:
  windows:
    name: "${{ matrix.display }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { display: "32-bit", bits: 32 }
          - { display: "64-bit", bits: 64 }
          #- { display: "64-bit (ARM)", bits: arm64 }
    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build nasm 7zip

      - name: Download toolchain
        run: |
          sudo ./packaging/download-llvm-mingw.sh /usr

      - name: Build
        run: |
          ./packaging/winbuild.sh ${{ matrix.bits }}

      - name: Upload output as artifact
        uses: actions/upload-artifact@v7
        with:
          name: principia_${{ matrix.bits }}.exe
          path: build_win${{ matrix.bits }}/principia_win${{ matrix.bits }}.exe
          #archive: false
          if-no-files-found: error

      - name: Upload output as artifact
        uses: actions/upload-artifact@v7
        with:
          name: principia_${{ matrix.bits }}.7z
          path: build_win${{ matrix.bits }}/principia_win${{ matrix.bits }}.7z
          #archive: false
          if-no-files-found: error
